puts "The students of Villains Academy"
puts "-----------------"
puts "Dr. Hannibal Lector"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Kreuger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
# We print the total number of students
print "Overall, we have "
# Important that print() doesn't add new line characters"
print 11
puts " great students"
